version: "3.3"

services:
  control:
    build: ./src/control
    image: leozz37/control
    container_name: control
    network_mode: "host"
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  broker:
    image: eclipse-mosquitto
    container_name: mqtt-mosquitto
    network_mode: "host"
    ports:
      - 1883:1883
      - 9001:9001

  sw-config:
    build: ./src/sw-config
    image: leozz37/sw-config
    container_name: sw-config
    network_mode: "host"
    stdin_open: true
    tty: true

  raspberry:
    build: ./src/raspberry
    image: leozz37/raspberry
    container_name: raspberry
    network_mode: "host"
