version: "3.8"

services:
  control:
    build: ./control
    image: leozz37/control
    container_name: control
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
