version: "3.3"

services:
  control:
    build: ./src/control
    image: leozz37/control
    container_name: control
    network_mode: "host"
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  broker:
    image: eclipse-mosquitto
    network_mode: "host"
    ports:
      - 1883:1883
      - 9001:9001
